### ISSUE TITLE
How do I get the top line of things to work in c3270?

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/c3270port#1]
File / Options / Keypad is across the top, but I can't figure out how to use them...

**Comment by gngrossi** [comment]
Ctrl-n will access the File Menu and Ctrl-k will access the Keypad Menu.
Once in the File Menu, the right arrow keyboard key can be used to go to Options and Keypad.
Also, the mouse click allows access to each menu. Using the Esc keyboard key seems to exit the menus.

Other keyboard navigation keys seem to work:
Ctrl-j		newline
Ctrl-h		backspace
Ctrl-c		clear
Ctrl-a + Tab	back tab
Ctrl-a r             reset

https://x3270.miraheze.org/wiki/C3270

**Comment by MikeFultonDev** [comment]
Perfect! Thanks @gngrossi
