### ISSUE TITLE
man pages

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/c3270port#2]
Installed c3270 and ran mandb

bash-5.2$ which c3270
/hewitt/zopentools/guild/c3270/bin/c3270

bash-5.2$ man c3270
No manual entry for c3270
No manual entry for c3270

**Comment by MikeFultonDev** [comment]
@gngrossi does this work with the latest drop?

**Comment by MikeFultonDev** [comment]
This is what I see:
![image](https://github.com/ZOSOpenTools/c3270port/assets/61100689/b4ed1766-2978-4a2f-9873-d4718a2f4426)

**Comment by IgorTodorovskiIBM** [comment]
Should be fixed via https://github.com/ZOSOpenTools/c3270port/pull/3

**Comment by gngrossi** [comment]
Please confirm, one man page? If so, I will close.
thanks

**Comment by MikeFultonDev** [comment]
@gngrossi just checked this again - there are a bunch of man pages now for s3270, c3270... So I think we're good. Please re-open if you see issues still.

**Comment by gngrossi** [comment]
OK, this is what's returned from man c3270 (also 20 lines for man s3270).
thanks

![image](https://github.com/ZOSOpenTools/c3270port/assets/115715798/4cdd913e-a340-442e-b044-2d2c61e807bf)
